### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/caesar-cipher#7]
```sh
[20:59:09] 🐍 Python dependencies were installed from /app/caesar-cipher/Pipfile using pipenv.
Check if streamlit is installed
Streamlit is already installed
[20:59:10] 📦 Processed dependencies!
Traceback (most recent call last):
  File "/home/appuser/venv/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/__init__.py", line 57, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/delta_generator.py", line 46, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
[21:00:49] ❗️ Streamlit server consistently failed status checks
[21:00:49] ❗️ Please fix the errors, push an update to the git repo, or reboot the app.
```

Notes
* https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/4
* https://github.com/streamlit/streamlit/issues/6215
* https://discuss.huggingface.co/t/streamlit-spaces-with-modulenotfounderror-no-module-named-altair-vegalite-v4-error/39683/2

**Comment by jelaiw** [comment]
Require altair<5 per https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/4.
